# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16138204968602894b6ccb6760ac7c9c9233094469795b45147b627c3eb12783a1afca2439c5605f6571fa928dcd7b9b7847ab8c00b5bc2a66c5f2073990f828

test:
  secret_key_base: 8bd85bf9d606bb601941cee669ef61b12dc253579b16954df0918a973e5e07d2fffbd096f2c3d275caf335e7169cd75ee01ff884821e5218b4c1cd09219bb07d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
